// Código corrigido e funcional para o experimento
!function(){"use strict";
var e="ee6a453b-81e0-404f-8e7a-314331464704",t="https://rotafinal.com.br",
n=function(){var e=localStorage.getItem("rf_user_id");return e||(e="rf_"+Math.random().toString(36).substr(2,9)+"_"+Date.now().toString(36),localStorage.setItem("rf_user_id",e)),e},
r=function(){return/bot|crawler|spider|crawling/i.test(navigator.userAgent)},
o=function(e,t){var n={headers:{"Content-Type":"application/json","X-RF-Version":"2.0.0"}};return fetch(e,Object.assign(n,t)).then(function(e){if(!e.ok)throw new Error("HTTP "+e.status+": "+e.statusText);return e.json()})},
a={cachedVariant:null,fetchVariant:function(){var n=this;return this.cachedVariant?Promise.resolve(this.cachedVariant):o(t+"/api/experiments/"+e+"/assign",{method:"POST",body:JSON.stringify({visitor_id:n(),user_agent:navigator.userAgent,url:window.location.href,referrer:document.referrer,timestamp:new Date().toISOString(),viewport:{width:window.innerWidth,height:window.innerHeight}})})},applyVariant:function(e){if(!e)return;document.documentElement.setAttribute("data-rf-experiment",e),document.documentElement.setAttribute("data-rf-variant",e.name||"control"),document.documentElement.setAttribute("data-rf-user",n()),e.redirect_url&&(window.location.href=e.redirect_url)}},
i={eventQueue:[],track:function(e,t){var n={experiment_id:e,visitor_id:n(),event_type:e,properties:t,timestamp:new Date().toISOString(),url:window.location.href,referrer:document.referrer,user_agent:navigator.userAgent,variant:a.cachedVariant&&a.cachedVariant.name||null};o(t+"/api/track",{method:"POST",body:JSON.stringify(n)}).catch(function(){i.eventQueue.push(n)})},flushQueue:function(){if(0===this.eventQueue.length)return;var e=this.eventQueue;this.eventQueue=[],o(t+"/api/track/batch",{method:"POST",body:JSON.stringify({events:e})}).catch(function(){i.eventQueue=e})},trackPageview:function(){this.track("page_view",{title:document.title,path:window.location.pathname,search:window.location.search})},setupClickTracking:function(){document.addEventListener("click",function(e){var t=e.target.closest("[data-rf-track]");if(t){var n=t.getAttribute("data-rf-track")||"click",r={};Array.from(t.attributes).forEach(function(e){e.name.startsWith("data-rf-")&&"data-rf-track"!==e.name&&(r[e.name.replace("data-rf-","")]=e.value)}),i.track(n,Object.assign({element:t.tagName.toLowerCase(),text:(t.textContent||"").trim().substr(0,100)},r))}})}},
c=function(){if(r())return;o(t+"/api/experiments/"+e+"/assign").then(function(e){a.applyVariant(e.variant)}).catch(function(){}).finally(function(){document.documentElement.setAttribute("data-rf-ready","true");var e=document.querySelector("style[data-rf-antiflicker]");e&&setTimeout(function(){e.remove()},100)})};
window.RotaFinal={track:function(e,t){return i.track(e,t)},convert:function(e,t){return this.track("conversion",Object.assign({value:e},t))},getVariant:function(){return a.cachedVariant},getUserId:n,reload:function(){a.cachedVariant=null,c()},setDebug:function(e){}};
window.addEventListener("beforeunload",function(){i.flushQueue()});
"loading"===document.readyState?document.addEventListener("DOMContentLoaded",c):c();
}();
