// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/callback" | "/auth/signin" | "/dashboard" | "/dashboard/events" | "/dashboard/experiments" | "/dashboard/goals" | "/dashboard/projects" | "/dashboard/visitors" | "/experiments/[id]" | "/settings"
type AppRouteHandlerRoutes = "/api/assign-variant" | "/api/auth/confirm-email" | "/api/debug/constraints/[table]" | "/api/debug/schema/[table]" | "/api/device-breakdown" | "/api/experiments" | "/api/experiments/[id]" | "/api/experiments/[id]/assign" | "/api/experiments/[id]/public" | "/api/experiments/[id]/stats" | "/api/experiments/[id]/status" | "/api/experiments/[id]/variants" | "/api/experiments/create-direct" | "/api/funnel-data" | "/api/get-metrics" | "/api/health" | "/api/revenue-data" | "/api/settings/custom-domains" | "/api/test" | "/api/test-simple" | "/api/test-supabase" | "/api/test/experiments" | "/api/test/experiments-simple" | "/api/track" | "/api/track-event" | "/api/track/batch" | "/api/visitor-trends" | "/rotafinal-sdk.js"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/assign-variant": {}
  "/api/auth/confirm-email": {}
  "/api/debug/constraints/[table]": { "table": string; }
  "/api/debug/schema/[table]": { "table": string; }
  "/api/device-breakdown": {}
  "/api/experiments": {}
  "/api/experiments/[id]": { "id": string; }
  "/api/experiments/[id]/assign": { "id": string; }
  "/api/experiments/[id]/public": { "id": string; }
  "/api/experiments/[id]/stats": { "id": string; }
  "/api/experiments/[id]/status": { "id": string; }
  "/api/experiments/[id]/variants": { "id": string; }
  "/api/experiments/create-direct": {}
  "/api/funnel-data": {}
  "/api/get-metrics": {}
  "/api/health": {}
  "/api/revenue-data": {}
  "/api/settings/custom-domains": {}
  "/api/test": {}
  "/api/test-simple": {}
  "/api/test-supabase": {}
  "/api/test/experiments": {}
  "/api/test/experiments-simple": {}
  "/api/track": {}
  "/api/track-event": {}
  "/api/track/batch": {}
  "/api/visitor-trends": {}
  "/auth/callback": {}
  "/auth/signin": {}
  "/dashboard": {}
  "/dashboard/events": {}
  "/dashboard/experiments": {}
  "/dashboard/goals": {}
  "/dashboard/projects": {}
  "/dashboard/visitors": {}
  "/experiments/[id]": { "id": string; }
  "/rotafinal-sdk.js": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
