// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/experiments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/experiments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/experiments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/goals">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/visitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/visitors">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/visitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/experiments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experiments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/experiments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assign-variant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assign-variant">> = Specific
  const handler = {} as typeof import("../../src/app/api/assign-variant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/confirm-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/confirm-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/confirm-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/constraints/[table]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/constraints/[table]">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/constraints/[table]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/schema/[table]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/schema/[table]">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/schema/[table]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/device-breakdown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/device-breakdown">> = Specific
  const handler = {} as typeof import("../../src/app/api/device-breakdown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/public">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/[id]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/variants">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/[id]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/create-direct/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/create-direct">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/create-direct/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/experiments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments">> = Specific
  const handler = {} as typeof import("../../src/app/api/experiments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/funnel-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funnel-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/funnel-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/get-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/get-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/get-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revenue-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revenue-data">> = Specific
  const handler = {} as typeof import("../../src/app/api/revenue-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/custom-domains/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/custom-domains">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/custom-domains/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-simple/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-simple">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-simple/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-supabase">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test/experiments-simple/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/experiments-simple">> = Specific
  const handler = {} as typeof import("../../src/app/api/test/experiments-simple/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test/experiments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/experiments">> = Specific
  const handler = {} as typeof import("../../src/app/api/test/experiments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track-event">> = Specific
  const handler = {} as typeof import("../../src/app/api/track-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track/batch">> = Specific
  const handler = {} as typeof import("../../src/app/api/track/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/visitor-trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitor-trends">> = Specific
  const handler = {} as typeof import("../../src/app/api/visitor-trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rotafinal-sdk.js/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rotafinal-sdk.js">> = Specific
  const handler = {} as typeof import("../../src/app/rotafinal-sdk.js/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
